#!/usr/bin/perl
use Mojolicious::Lite;

use Mojo::File 'path';
use Mojo::ByteStream 'b';

get '/' => 'upload';
post '/reconcile' => sub {
  my $c = shift;
  my $at = b($c->req->upload('at')->asset->slurp)->split("\n");
  my $qb = b($c->req->upload('qb')->asset->slurp)->split("\n");
  my $recon = reconcile($at, $qb);
  $c->render(recon => $recon);
};
app->start;

sub reconcile {
  my ($at, $qb) = @_;
  my %recon;
  $at->grep(qr/^\d+\t/)->each(sub {
    my ($batchid, $invoiceid, $invoice, $amount) = (/^(\d+)\t(\d+)\t(\d+)\.00\t(\d+\.\d{2})\r?\n?$/);
    $invoice ||= 0;
    $amount ||= 0;
    #warn "$batchid, $invoiceid, $invoice, $amount";
    my $amount_qb = $qb->grep(qr/\tInvoice\t/)->map(sub{@_ = split /\t/, $_; $_[18] =~ s/,//g; $_[18] =~ s/"//g; $_[18] =~ s/\r?//; $_=[$_[8],$_[14]?0:$_[18]]})->grep(sub{$_->[0] eq $invoice})->first;
    $recon{$invoice} ||= [0,0];
    $recon{$invoice}->[0] += $amount;
    $recon{$invoice}->[1] += $amount_qb->[1]||0;
  });
  return \%recon;
}

__DATA__
@@ upload.html.ep
<pre>
Upload the attached at.csv to the Autotask file field and qb.tsv to the Quickbooks file field and then click Ok.  You'll get the results in a nice table form!  Let me know how you'd like this improved.  As usual, it's not pretty.  :)

You already know how to generate your Quickbooks reports.  You'll need to export the sheet to a Tab-Separated .TSV file.  I'll be able to do the conversion eventually, but for now, please take this extra step.
For the Autotask Report, go to (A) > Contracts > Live Reports > Invoice Reconciliation and then run the report.  It defaults to last month.  See the screenshot below.  You'll need to export the sheet to a Tab-Separated .TSV file.  I'll be able to do the conversion eventually, but for now, please take this extra step.

Once you have both .tsv files, upload them using the web url above and press ok.  That should be all!

I have only one test case, so for this to work, the QB report form and the AT report format must never change.  There is no error handling, which means that if there's an error, who knows what will go wrong.  Don't worry about it, just let me know.  I'm hoping that for the most part you can just run your reports and convert to .tsv and upload them to get the reconciliation whenever you want.  If you do it enough, let me know I'll increase the priority on handling the Excel to .TSV conversion automatically so that you need only run the reports and immediately upload them.
</pre>
%= form_for 'reconcile' => (enctype => 'multipart/form-data') => begin
  %= label_for at => 'Autotask Report'
  %= file_field 'at'
  %= label_for at => 'Quickbooks Report'
  %= file_field 'qb'
  %= submit_button
% end

@@ reconcile.html.ep
% my $diff = 0;
<table>
<tr><th>Invoice Number</th><th>Autotask</th><th>Quickbooks</th><th>Difference</th></tr>
% foreach my $invoice ( sort keys %$recon ) {
%   my ($at, $qb) = @{$recon->{$invoice}};
%   if ( $at ne $qb ) {
%     $diff++;
      <tr><td><%= $invoice %></td><td><%= $at %></td><td><%= $qb %></td><td><%= $at - $qb %></td></tr>
%   }
% }
</table>
% unless ( $diff ) {
There are no Invoice differences between Autotask and Quickbooks for the selected date range. Autotask and Quickbooks are 100% reconciled!
% }
